# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.

handlers = 1catalina.org.apache.juli.AsyncFileHandler, \
           2localhost.org.apache.juli.AsyncFileHandler, \
           3manager.org.apache.juli.AsyncFileHandler, \
           4host-manager.org.apache.juli.AsyncFileHandler, \
           java.util.logging.ConsoleHandler

.handlers = 1catalina.org.apache.juli.AsyncFileHandler, \
            java.util.logging.ConsoleHandler

############################################################
# Handler specific properties.
############################################################

1catalina.org.apache.juli.AsyncFileHandler.level = FINEST
1catalina.org.apache.juli.AsyncFileHandler.directory = /ebiz/app_logs/tomcat
1catalina.org.apache.juli.AsyncFileHandler.prefix = catalina.
1catalina.org.apache.juli.AsyncFileHandler.maxDays = 30

2localhost.org.apache.juli.AsyncFileHandler.level = FINEST
2localhost.org.apache.juli.AsyncFileHandler.directory = /ebiz/app_logs/tomcat
2localhost.org.apache.juli.AsyncFileHandler.prefix = localhost.
2localhost.org.apache.juli.AsyncFileHandler.maxDays = 30

3manager.org.apache.juli.AsyncFileHandler.level = FINEST
3manager.org.apache.juli.AsyncFileHandler.directory = /ebiz/app_logs/tomcat
3manager.org.apache.juli.AsyncFileHandler.prefix = manager.
3manager.org.apache.juli.AsyncFileHandler.maxDays = 30

4host-manager.org.apache.juli.AsyncFileHandler.level = FINEST
4host-manager.org.apache.juli.AsyncFileHandler.directory = /ebiz/app_logs/tomcat
4host-manager.org.apache.juli.AsyncFileHandler.prefix = host-manager.
4host-manager.org.apache.juli.AsyncFileHandler.maxDays = 30

java.util.logging.ConsoleHandler.level = FINEST
java.util.logging.ConsoleHandler.formatter = org.apache.juli.OneLineFormatter

############################################################
# Facility specific properties.
############################################################

org.apache.catalina.core.ContainerBase.[Catalina].[localhost].level = INFO
org.apache.catalina.core.ContainerBase.[Catalina].[localhost].handlers = \
        2localhost.org.apache.juli.AsyncFileHandler

org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/manager].level = INFO
org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/manager].handlers = \
        3manager.org.apache.juli.AsyncFileHandler

org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/host-manager].level = INFO
org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/host-manager].handlers = \
        4host-manager.org.apache.juli.AsyncFileHandler

############################################################
# Authentication / Authorization Troubleshooting
############################################################

# Base realm logging
org.apache.catalina.realm.level = FINEST
org.apache.catalina.realm.handlers = \
        1catalina.org.apache.juli.AsyncFileHandler

# JNDI Realm logging
org.apache.catalina.realm.JNDIRealm.level = FINEST
org.apache.catalina.realm.JNDIRealm.handlers = \
        1catalina.org.apache.juli.AsyncFileHandler

# Form / BASIC auth processing
org.apache.catalina.authenticator.level = FINEST
org.apache.catalina.authenticator.handlers = \
        1catalina.org.apache.juli.AsyncFileHandler

# Security constraint evaluation
org.apache.catalina.core.level = FINE
org.apache.catalina.core.handlers = \
        1catalina.org.apache.juli.AsyncFileHandler
